opendevstack/ods-provisioning-app

- ocp-config/prov-dev/bc.yml
It's not present in prov-test either and breaks the build.
> Remove secrets key

- ocp-config/prov-cd/bc.yml
That way, the user already has a production Jenkins pipeline which can
be triggered easily. It is likely that many users will not make any
commits in the provisioning app repo, and therefore not pipeline will be
created.
Closes #68.
> Add production pipeline

- build.gradle
Fixes #154
The Guava version has been changed to the latest version containing the Objects.ToStringHelper
> - Implemented: changed Guava version

- src/main/java/org/opendevstack/provision/storage/LocalStorage.java
getProject is returning always a project even if the requested project does not exist.
This patch fixes this issue
> Fix for getProject

- build.gradle
Reverts opendevstack/ods-provisioning-app#218 , since this change breaks the entire navigation bar.
Changes between bootstrap v3.x.x and  v4.0.0 are documented at https://getbootstrap.com/docs/4.0/migration/#by-component
Migrating to v4. has to be implemented and tested carefully.
> Revert "Bump bootstrap from 3.3.7 to 4.3.1"

- ocp-config/prov-app/cm.yml
- src/main/java/org/opendevstack/provision/services/JenkinsPipelineAdapter.java
- src/main/resources/application.properties
- src/main/resources/templates/provision.html
There is some overlap now with the configuration of the quickstarters, but I don't want to change that before @stefanlack your changes with the description are in.
This change allows to configure the ref/image to use e.g. in the quickstarter Jenkinsfiles, which makes it quite easy to change out new stuff :)
> Configure ods image and ref

- src/main/java/org/opendevstack/provision/util/rest/RestClientCall.java
- src/test/java/org/opendevstack/provision/services/CleanupAtlassianProjectsMT.java
> add simple manual test that can be used to clean up  atlassian resources

- src/main/java/org/opendevstack/provision/services/JenkinsPipelineAdapter.java
The Jenkins job can use it to figure out if the
passed user is the general one or a project specific one.
Addresses https://github.com/opendevstack/ods-core/issues/314.
> Add CD_USER_TYPE param

- src/main/java/org/opendevstack/provision/controller/ProjectApiController.java
FYI @stitakis @clemensutschig @herrkoch This fixes yet another flow that was not handled correctly ... in theory there can be more placed like this ... but in testing this seems to be it. We must find another way to deal with the whole thing in ODS 3.
> Catch custom exception early to return 401

- ocp-config/prov-app/dc.yml
As the deployment happens via Jenkins, the "latest" tag is set.
While we still have the prov-dev/prov-test setup, this is the best
configuration. If and when there is a prov-app installation in the "cd"
namespace, then this should probably be tagged with ODS_IMAGE_TAG. But
will do that then ...
Fixes #331 for 2.x.
> Use image tag "latest" for prov-app for 2.x

- ocp-config/prov-app/dc.yml
As the deployment happens via Jenkins, the "latest" tag is set.
While we still have the prov-dev/prov-test setup, this is the best
configuration. If and when there is a prov-app installation in the "cd"
namespace, then this should probably be tagged with ODS_IMAGE_TAG. But
will do that then ...
Fixes #331.
> Use image tag "latest" for prov-app

- .github/workflows/gradle.yml
- build.gradle
- docker/Dockerfile
switches java version to 11 and uses the adoptopenjdk 11 image based on UBI minimal.
For more information on UBI see https://www.redhat.com/en/blog/introducing-red-hat-universal-base-image.
> switch to java 11 and use adoptopenjdk 11 image based on UBI minimal

- ocp-config/prov-app/cm.yml
- src/main/resources/logback-spring.xml
Fixes #384 
Adds backward compatibility for logback configuration. File path defaults to old value.
> adds default value for logback file path backport 2.x

- ocp-config/prov-app/dc.yml
Typical memory usage seems to hover around 350Mi, so using 512Mi/1Gi
should be fine.
Typical CPU usage is well below 100m - however during boot, it is really
helpful to have lots of CPU available, therefore we limit to 1 core.
Fixes #396.
> Specify resource constraints on DeploymentConfig

- .github/workflows/gradle.yml
- .github/workflows/push-image.sh
This PR adds building and pushing of the docker image to https://hub.docker.com/repository/docker/opendevstackorg/ods-provisioning-app to the GH CI workflow.
> Add building and pushing the docker image to CI workflow

- openshift/cm.yml
- src/main/java/org/opendevstack/provision/services/BitbucketAdapter.java
- src/main/java/org/opendevstack/provision/services/JenkinsPipelineAdapter.java
- src/main/resources/application.properties
- src/test/java/org/opendevstack/provision/controller/E2EProjectAPIControllerTest.java
- src/test/java/org/opendevstack/provision/services/JenkinsPipelineAdapterTest.java
Adds a separate configuration for the admin webhookproxy that proxies the create and delete project jobs defaulting to `webhook-proxy-ods`.
For the project webhook proxies that are created with each new project the pattern is still the same `webhook-proxy-${PROJECT_ID}-cd`
> add separate configuration for admin webhookproxy

- .github/workflows/gradle.yml
Resolves #441
@clemensutschig @michaelsauter I changed `ods.build.source.repo.branch` to `ods.build.source.repo.ref` as builds on github might come from tags as well.
IMHO we should change the key in the shared lib as well.
I also changed `ods.build.jenkins.job.url` to `ods.build.jenkins.job.url`.
> add docker labels to image

- src/main/java/org/opendevstack/provision/controller/ProjectApiController.java
- src/main/java/org/opendevstack/provision/model/OpenProjectData.java
- src/test/java/org/opendevstack/provision/controller/E2EProjectAPIControllerTest.java
fixes #547 
very surgical fix - remove the quickstarters - and update the storage. 
Tests cover this now - including checking the response, as well as retrieving the project and verifying the quickstarters are not there anymore.
> delete components now removes the quickstarters also from the storage

- src/main/java/org/opendevstack/provision/services/JenkinsPipelineAdapter.java
- src/test/java/org/opendevstack/provision/services/JenkinsPipelineAdapterTest.java
Otherwise the `ALLOWED_EXTERNAL_PROJECTS` value of the webhook proxy is not set correctly for Bitbucket projects other than `OPENDEVSTACK`, which prevents components from being provisioned correctly.
> Pass ODS_BITBUCKET_PROJECT to jobs

- docker/Dockerfile
instead of `openjdk11:ubi-minimal-jre`
fixes #588 (ported from branch 3.x)
> replaces base image to adoptopenjdk/openjdk11:ubi-jre

- docker/Dockerfile
> replaces docker image from openjdk11:ubi-jre

- build.gradle
- docs/modules/provisioning-app/pages/configuration.adoc
- src/main/java/org/opendevstack/provision/config/OpenshiftServiceConfig.java
- src/main/java/org/opendevstack/provision/controller/ProjectApiController.java
- src/main/java/org/opendevstack/provision/services/openshift/OpenshiftClient.java
- src/main/java/org/opendevstack/provision/services/openshift/OpenshiftService.java
- src/main/resources/application-odsbox.properties
- src/main/resources/application.properties
- src/test/java/org/opendevstack/provision/config/OpenshiftServiceConfigTest.java
- src/test/java/org/opendevstack/provision/controller/E2EProjectAPIControllerTest.java
- src/test/java/org/opendevstack/provision/controller/ProjectApiControllerTest.java
- src/test/java/org/opendevstack/provision/services/openshift/OpenshiftClientTest.java
- src/test/java/org/opendevstack/provision/services/openshift/OpenshiftServiceTest.java
- src/test/resources/application-crowd.properties
- src/test/resources/application-utest.properties
- src/test/resources/oc-token
> adds openshift project key preflight check

- CHANGELOG.md
- docs/modules/provisioning-app/pages/configuration.adoc
- src/main/resources/application.properties
- src/main/resources/templates/fragments/header.html
Resolves #706 
Added a property to define the disclaimer text. And a text in the header component to be displayed in all the screens in case it is defined.
> feature: enable a configurable disclaimer in the UI with a new property

- CHANGELOG.md
- src/main/java/org/opendevstack/provision/model/bitbucket/Repository.java
- src/main/java/org/opendevstack/provision/services/BitbucketAdapter.java
- src/test/java/org/opendevstack/provision/services/BitbucketAdapterTest.java
I never understood why we did not seed the component description into the repo ... (as it's possible) .. but here it finally is...
> add missing bitbucket repository description on repository creation event

- CHANGELOG.md
- docs/modules/provisioning-app/pages/configuration.adoc
- docs/modules/provisioning-app/pages/index.adoc
- src/main/java/org/opendevstack/provision/services/BitbucketAdapter.java
- src/main/resources/application-odsbox.properties
- src/main/resources/application.properties
- src/test/java/org/opendevstack/provision/services/BitbucketAdapterTest.java
- src/test/resources/application-utest.properties
fixes #700 port to 4.x
* Only set admin permissions at repo level, if special permission set was not specified on project creation.
* Assign admin permissions to the default admin group when a specific one
wasn not specified
* The admin group defaults to the user group in the application.properties
file.
Co-authored-by: zxBCN Farre_Basurte,Juan_Antonio (IT EDS) EXTERNAL <juan_antonio.farre_basurte.ext@boehringer-ingelheim.com>
> Backport: Fix problem assigning admin permissions to bitbucket repositories
