gradle/wrapper/gradle-wrapper.properties
Gradle 3.3 does not work with Java 10.0.1.
=> Update Gradle to 4.9

src/main/java/org/opendevstack/provision/services/RundeckAdapter.java
=> rundeck error bubble #7

src/main/java/org/opendevstack/provision/services/JiraAdapter.java, src/main/resources/.gitignore, src/main/resources/permission-templates/jira.permission.all.txt
extension to the current - very basic role/permissionscheme
=> additional jira permissions - for special roleset

src/main/java/org/opendevstack/provision/controller/ProjectApiController.java, src/main/java/org/opendevstack/provision/model/ProjectData.java, src/main/java/org/opendevstack/provision/services/RundeckAdapter.java, src/main/resources/static/js/client.js, src/main/resources/templates/provision.html
Half merge - pushed incomplete ...  fixes #32
=> Feature/show executions - follow up

Jenkinsfile
=> Point to production branch of shared library

Jenkinsfile
=> Adjust Jenkinsfile to latest production shared lib

src/main/java/org/opendevstack/provision/controller/ProjectApiController.java, src/main/resources/templates/provision.html, src/test/java/org/opendevstack/provision/controller/ProjectApiControllerTest.java
fixes #64 - verified at BI on premise
=> add checks and correction for desc.length > 100

.gitignore, src/main/java/org/opendevstack/provision/util/CrowdCookieJar.java, src/main/resources/application.properties, src/main/resources/logback-spring.xml, src/test/java/org/opendevstack/provision/util/CrowdCookieJarTest.java, src/test/java/org/opendevstack/provision/util/RestClientTest.java
=> make crowd sso cookie name configurable (1.0.x)

.gitignore, src/main/java/org/opendevstack/provision/util/CrowdCookieJar.java, src/main/resources/application.properties, src/main/resources/logback-spring.xml, src/test/java/org/opendevstack/provision/util/CrowdCookieJarTest.java, src/test/java/org/opendevstack/provision/util/RestClientTest.java
=> make crowd sso cookie name configurable (master)

src/main/java/org/opendevstack/provision/services/BitbucketAdapter.java, src/test/java/org/opendevstack/provision/services/BitbucketAdapterTest.java
2 line bug fix on rights (roles).
Closes #87.
=> remove default user group (admin rights) on created BB project when createpermissionset==true (master)

src/main/java/org/opendevstack/provision/services/BitbucketAdapter.java, src/test/java/org/opendevstack/provision/services/BitbucketAdapterTest.java
=> remove default user group (admin rights) on created BB project when createpermissionset==true (1.0.x)

ocp-config/prov-cd/pvc.yml
=> right storageClassName loaded param name

ocp-config/prov-cd/pvc.yml
=> update storageClassName loaded parameter name

src/main/java/org/opendevstack/provision/model/jira/FullJiraProject.java, src/main/java/org/opendevstack/provision/services/JiraAdapter.java, src/main/resources/application.properties, src/test/java/org/opendevstack/provision/services/BitbucketAdapterTest.java, src/test/java/org/opendevstack/provision/services/JiraAdapterTests.java
=> add notification set and fix broken test on master 

src/main/java/org/opendevstack/provision/model/jira/FullJiraProject.java, src/main/java/org/opendevstack/provision/services/JiraAdapter.java, src/main/resources/application.properties, src/test/java/org/opendevstack/provision/services/JiraAdapterTests.java
=> add default notification scheme - 1.0.x

CHANGELOG.md, README.md, src/main/java/org/opendevstack/provision/services/RundeckAdapter.java, src/test/java/org/opendevstack/provision/services/RundeckAdapterTest.java
prov app contribution to opendevstack/ods-project-quickstarters#112
=> pass entitlement groups and amend .md

docs/antora.yml, docs/modules/ROOT/pages/index.adoc
=> doc changes based on antorra for 1.0.x

docs/antora.yml, docs/modules/ROOT/nav.adoc, docs/modules/ROOT/pages/index.adoc
=> Creation of antora documentation module

CHANGELOG.md, build.gradle, ocp-config/prov-app/cm.yml, src/main/java/org/opendevstack/provision/controller/ProjectApiController.java, src/main/java/org/opendevstack/provision/services/BitbucketAdapter.java, src/main/java/org/opendevstack/provision/services/ConfluenceAdapter.java, src/main/java/org/opendevstack/provision/services/JiraAdapter.java, src/main/resources/application.properties, src/test/java/org/opendevstack/provision/controller/ProjectApiControllerTest.java, src/test/java/org/opendevstack/provision/services/BitbucketAdapterTest.java
=> add kanban board config and new operation to resolve template keys

.travis.yml, build.gradle
Travis CI config and gradle build adjustment to be able to build / test on Travis CI.
=> Travis CI build setup

CHANGELOG.md, src/main/java/org/opendevstack/provision/authentication/SimpleCachingGroupMembershipManager.java, src/main/java/org/opendevstack/provision/config/SecurityConfiguration.java, src/main/java/org/opendevstack/provision/controller/DefaultController.java, src/main/java/org/opendevstack/provision/services/ProjectIdentityMgmtAdapter.java, src/main/resources/templates/provision.html, src/test/java/org/opendevstack/provision/authentication/SimpleCachingGroupMembershipManagerTest.java
=> performance cache fix - for master

src/main/java/org/opendevstack/provision/authentication/SimpleCachingGroupMembershipManager.java, src/main/java/org/opendevstack/provision/config/SecurityConfiguration.java, src/main/java/org/opendevstack/provision/controller/DefaultController.java, src/main/java/org/opendevstack/provision/services/ProjectIdentityMgmtAdapter.java, src/test/java/org/opendevstack/provision/authentication/SimpleCachingGroupMembershipManagerTest.java
=> performance cache fix - for 1.0.x

src/main/java/org/opendevstack/provision/controller/ProjectApiController.java, src/main/java/org/opendevstack/provision/services/BitbucketAdapter.java, src/main/java/org/opendevstack/provision/services/ConfluenceAdapter.java, src/main/java/org/opendevstack/provision/services/JiraAdapter.java, src/main/java/org/opendevstack/provision/services/MailAdapter.java, src/main/java/org/opendevstack/provision/services/ProjectIdentityMgmtAdapter.java, src/main/java/org/opendevstack/provision/services/RundeckAdapter.java, src/main/java/org/opendevstack/provision/services/StorageAdapter.java
Refactored adpaters in package _org.opendevstack.provision.services_ to improve code quality.
=> Refaoring of Adapters

CHANGELOG.md, ocp-config/prov-app/cm.yml, src/main/java/org/opendevstack/provision/services/JiraAdapter.java, src/main/java/org/opendevstack/provision/util/RestClient.java, src/main/resources/application.properties, src/main/resources/static/js/client.js
=> Bug/sso direct 

README.md, build.gradle
- Nexus can also be disabled using a gradle property. 
- Documented environment variables used by the gradle build.
- Added Travis build status to readme.
=> Generalize maven repository selection

src/main/java/org/opendevstack/provision/util/RestClient.java
=> fix rundeckauth error - for master

src/main/java/org/opendevstack/provision/services/RundeckAdapter.java
=> fix rundeckauth error check - for 1.0.x

src/main/java/org/opendevstack/provision/authentication/SimpleCachingGroupMembershipManager.java, src/main/java/org/opendevstack/provision/util/RestClient.java
=> add 409 HTTP Err code to retry list and bump down log level in idmgmt

src/main/resources/application.properties, src/test/java/org/opendevstack/provision/services/RundeckAdapterTest.java
Fix properties, done together with Torsten
=> Fix properties

CHANGELOG.md, build.gradle, src/main/java/org/opendevstack/provision/controller/ProjectApiController.java, src/main/java/org/opendevstack/provision/model/Component.java, src/main/java/org/opendevstack/provision/model/ProjectData.java, src/main/java/org/opendevstack/provision/services/JiraAdapter.java, src/main/java/org/opendevstack/provision/util/RestClient.java, src/test/java/org/opendevstack/provision/controller/ProjectApiControllerTest.java, src/test/java/org/opendevstack/provision/services/BitbucketAdapterTest.java, src/test/java/org/opendevstack/provision/services/JiraAdapterTests.java, src/test/resources/data/repositoryTestData.txt
=> bugfix for checking against existing projects and addition of jira component creation -> master

docs/antora.yml, docs/modules/ROOT/pages/index.adoc
Preview availabla at https://www.rattermeyer.de/ods-documentation
=> Added antora documentation to 1.1.x

docs/modules/ROOT/pages/index.adoc
=> Links to source code corrected

README.md, src/main/resources/templates/crowdLogin.html
Detect Firefox separated from Internet Explorer.
fixed #110
=> Detect Firefox

src/main/java/org/opendevstack/provision/services/BaseServiceAdapter.java, src/main/java/org/opendevstack/provision/services/RundeckAdapter.java
=> - Implemented: fixed issue #239

src/main/resources/application-oauth2.properties
fix property spring.security.oauth2.client.provider.keycloak.authorization-uri
=> invalid property in application-oauth2.properties

src/main/java/org/opendevstack/provision/util/GitUrlWrangler.java, src/test/java/org/opendevstack/provision/util/GitUrlWranglerTest.java
=> GitUrlWrangler Class has some issues (bugfix)

.gitattributes
=> added gitattributes for CRLF handling

src/main/java/org/opendevstack/provision/adapter/IBugtrackerAdapter.java, src/main/java/org/opendevstack/provision/controller/ProjectApiController.java, src/main/java/org/opendevstack/provision/services/JiraAdapter.java, src/main/java/org/opendevstack/provision/services/RundeckAdapter.java, src/test/java/org/opendevstack/provision/controller/E2EProjectAPIControllerTest.java, src/test/java/org/opendevstack/provision/controller/ProjectApiControllerTest.java, src/test/java/org/opendevstack/provision/services/JiraAdapterTests.java
recrated #256 to prevent the CRLF issue.
@clemensutschig : if your are fine with this, you could approve this one and close the other.
=> recreated changes for #256

src/test/java/org/opendevstack/provision/controller/ProjectApiControllerTest.java
Hi Clemens,
I generated a diff using "git diff --ignore-cr-at-eol upstream/master" for your changes.
And took over the changes to the Java File.
Because you wanted to merge to master, the antora version remains at "latest" (was another diff).
If you are fine you could approve this one and close #254
=>  Feature/add legacy api test 

src/main/java/org/opendevstack/provision/services/RundeckAdapter.java
Create preAuthContent map for every request. (Previous code was valid if technical user is used, but for crowd based authentication the user and password may be changing for differnt calls of this method)
=> bugfix #264

src/main/java/org/opendevstack/provision/controller/ProjectApiController.java, src/main/java/org/opendevstack/provision/services/CrowdProjectIdentityMgmtAdapter.java, src/main/java/org/opendevstack/provision/services/JiraAdapter.java, src/main/java/org/opendevstack/provision/services/RundeckAdapter.java, src/test/java/org/opendevstack/provision/controller/E2EProjectAPIControllerTest.java
=> fix order of deletion for jira objects, and add new test

ocp-config/prov-app/Tailorfile.dev, ocp-config/prov-app/Tailorfile.test, ocp-config/prov-app/bc.yml, ocp-config/prov-app/cm.yml, ocp-config/prov-app/dc.yml, ocp-config/prov-app/route.yml, ocp-config/prov-app/secret.yml, ocp-config/prov-cd/Tailorfile, ocp-config/prov-cd/bc.yml, ocp-config/prov-cd/dc.yml, ocp-config/prov-cd/secret.yml
Uses the new, unified files and adds PROV_APP_ prefix to the params.
Relates to https://github.com/opendevstack/ods-core/issues/219.
I left the Rundeck stuff in on purpose ... just want to make it "work", we can kill all the Rundeck things later.
=> Adjust configuration to new config sample

ocp-config/prov-cd/secret.yml
=> Use base64 encoded cd_user secret

src/main/java/org/opendevstack/provision/controller/ProjectApiController.java, src/test/java/org/opendevstack/provision/controller/ProjectApiControllerTest.java
=> add upgrade when qs ONLY is passed

ocp-config/prov-cd/rolebinding.yml
=> updated rolebinding to new format

ocp-config/prov-app/bc.yml, ocp-config/prov-app/dc.yml, ocp-config/prov-cd/dc.yml
=> Adapt to ODS_IMAGE_TAG

ocp-config/prov-app/cm.yml, src/main/java/org/opendevstack/provision/adapter/IJobExecutionAdapter.java, src/main/java/org/opendevstack/provision/config/JenkinsPipelineProperties.java, src/main/java/org/opendevstack/provision/config/Quickstarter.java, src/main/java/org/opendevstack/provision/config/QuickstarterType.java, src/main/java/org/opendevstack/provision/controller/DefaultController.java, src/main/java/org/opendevstack/provision/controller/ProjectApiController.java, src/main/java/org/opendevstack/provision/controller/QuickstarterApiController.java, src/main/java/org/opendevstack/provision/model/rundeck/Job.java, src/main/java/org/opendevstack/provision/services/JenkinsPipelineAdapter.java, src/main/resources/application.properties, src/test/java/org/opendevstack/provision/controller/DefaultControllerTest.java, src/test/java/org/opendevstack/provision/controller/QuickstarterApiControllerTest.java
=> bugfix #280 Quickstarters are missing a description

src/main/java/org/opendevstack/provision/services/JenkinsPipelineAdapter.java
Closes #290.
FYI @henrjk 
FYI @kiwo That was broken .... :( the applied solution is not great, this really should be done at a central level when projects are loaded.
=> Fall back to global trigger secret

src/main/java/org/opendevstack/provision/adapter/IServiceAdapter.java, src/main/java/org/opendevstack/provision/config/JenkinsPipelineProperties.java, src/main/java/org/opendevstack/provision/controller/ProjectApiController.java, src/main/java/org/opendevstack/provision/model/ExecutionsData.java, src/main/java/org/opendevstack/provision/services/JenkinsPipelineAdapter.java, src/main/resources/application.properties, src/test/java/org/opendevstack/provision/controller/E2EProjectAPIControllerTest.java
=> reimplemented delete projects

build.gradle, src/test/java/org/opendevstack/provision/util/rest/RestClientTest.java
=> uptake 4.1.0 okhttp!

ocp-config/prov-app/cm.yml, src/main/java/org/opendevstack/provision/adapter/IJobExecutionAdapter.java, src/main/java/org/opendevstack/provision/config/JenkinsPipelineProperties.java, src/main/java/org/opendevstack/provision/config/Quickstarter.java, src/main/java/org/opendevstack/provision/config/QuickstarterType.java, src/main/java/org/opendevstack/provision/controller/DefaultController.java, src/main/java/org/opendevstack/provision/controller/ProjectApiController.java, src/main/java/org/opendevstack/provision/controller/QuickstarterApiController.java, src/main/java/org/opendevstack/provision/model/OpenProjectData.java, src/main/java/org/opendevstack/provision/services/JenkinsPipelineAdapter.java, src/main/resources/application.properties, src/test/java/org/opendevstack/provision/controller/DefaultControllerTest.java, src/test/java/org/opendevstack/provision/controller/E2EProjectAPIControllerTest.java, src/test/java/org/opendevstack/provision/controller/QuickstarterApiControllerTest.java, src/test/java/org/opendevstack/provision/services/JenkinsPipelineAdapterTest.java
=> Bugfix #296 added delete component feature

ocp-config/prov-app/cm.yml, src/main/java/org/opendevstack/provision/adapter/IJobExecutionAdapter.java, src/main/java/org/opendevstack/provision/model/OpenProjectData.java, src/main/java/org/opendevstack/provision/services/JenkinsPipelineAdapter.java, src/main/resources/application.properties, src/main/resources/static/js/client.js, src/main/resources/templates/mailTemplate.html, src/main/resources/templates/provision.html, src/test/java/org/opendevstack/provision/services/JenkinsPipelineAdapterTest.java
Closes #307
Closes #308
Closes #309
=> Improve project specific CD user instructions

ocp-config/prov-app/cm.yml
closes https://github.com/opendevstack/ods-quickstarters/issues/76
=> changing be-airflow to airflow-cluster

src/main/resources/static/js/client.js, src/main/resources/templates/mailTemplate.html
I would like to see this wording change (see PR #312).
=> improve wording

src/main/java/org/opendevstack/provision/adapter/IODSAuthnzAdapter.java, src/main/java/org/opendevstack/provision/authentication/ControllerAdviceExceptionHandler.java, src/main/java/org/opendevstack/provision/authentication/MissingCredentialsInfoException.java, src/main/java/org/opendevstack/provision/authentication/crowd/CrowdSecurityConfiguration.java, src/main/java/org/opendevstack/provision/config/ControllerAdviceExceptionHandler.java, src/main/java/org/opendevstack/provision/services/BaseServiceAdapter.java, src/main/java/org/opendevstack/provision/util/CredentialsInfo.java, src/main/resources/static/js/client.js, src/test/java/org/opendevstack/provision/controller/E2EProjectAPIControllerTest.java, src/test/java/org/opendevstack/provision/services/BitbucketAdapterTest.java, src/test/java/org/opendevstack/provision/services/ConfluenceAdapterTest.java, src/test/java/org/opendevstack/provision/services/JiraAdapterTests.java
=> Fix 318 session timeout

build.gradle, gradle/wrapper/gradle-wrapper.properties, src/test/java/org/opendevstack/provision/services/JiraAdapterTests.java
Upgrades Spring Boot and gradle version
=> Feature/upgrade to spring 2.2.2

CHANGELOG.md, ocp-config/prov-cd/dc.yml
=> Run webhook-proxy deployment config under jenkins serviceaccount for 2.x

ocp-config/prov-cd/dc.yml
=> Run webhook-proxy deployment config under jenkins serviceaccount

.gitignore, src/main/java/org/opendevstack/provision/controller/ProjectApiController.java, src/main/java/org/opendevstack/provision/services/JenkinsPipelineAdapter.java, src/main/resources/static/js/client.js, src/main/resources/templates/provision.html, src/test/java/org/opendevstack/provision/controller/E2EProjectAPIControllerTest.java, src/test/java/org/opendevstack/provision/controller/ProjectApiControllerTest.java, src/test/java/org/opendevstack/provision/services/JenkinsPipelineAdapterTest.java, src/test/resources/e2e/ods-update-project-python-qs-request.json
=> adds component id and component type validation rules and shortens pipeline execution url length

src/main/java/org/opendevstack/provision/controller/ProjectApiController.java, src/main/java/org/opendevstack/provision/storage/IStorage.java, src/main/java/org/opendevstack/provision/storage/LocalStorage.java, src/main/java/org/opendevstack/provision/util/exception/ProjectAlreadyExistsException.java, src/test/java/org/opendevstack/provision/controller/ProjectApiControllerTest.java
=> Bug/existing project cleanup - backport for ods2

src/main/java/org/opendevstack/provision/authentication/oauth2/Oauth2AuthenticationManager.java
There was a typo. The value was not corresponding to the setting in application-oauth2.properties
=> correct wrong @Value annotation value of Oauth2AuthenticationManage.userInfoUri

src/main/java/org/opendevstack/provision/controller/ProjectApiController.java, src/main/java/org/opendevstack/provision/model/OpenProjectDataValidator.java, src/main/java/org/opendevstack/provision/services/JenkinsPipelineAdapter.java, src/main/resources/templates/provision.html, src/test/java/org/opendevstack/provision/controller/ProjectApiControllerTest.java, src/test/java/org/opendevstack/provision/model/OpenProjectDataValidatorTest.java, src/test/java/org/opendevstack/provision/services/JenkinsPipelineAdapterTest.java
=> adds component id name validation in UI and BE according to kubernetes lable naming specification

ocp-config/prov-app/cm.yml, src/main/resources/application.properties, src/main/resources/logback-spring.xml
=> fixes hardcoded logback file path and failed test when running locally

src/main/java/org/opendevstack/provision/authentication/oauth2/Oauth2LogoutHandler.java, src/main/java/org/opendevstack/provision/authentication/oauth2/Oauth2SecurityConfiguration.java, src/test/java/org/opendevstack/provision/authentication/oauth2/Oauth2LogoutHandlerLogoutFromIDMTest.java, src/test/java/org/opendevstack/provision/authentication/oauth2/Oauth2LogoutHandlerTest.java
=> adds option to disable logout from identity manager

src/main/java/org/opendevstack/provision/adapter/IServiceAdapter.java, src/main/java/org/opendevstack/provision/adapter/exception/AdapterException.java, src/main/java/org/opendevstack/provision/adapter/exception/CreateProjectPreconditionException.java, src/main/java/org/opendevstack/provision/controller/ProjectApiController.java, src/main/java/org/opendevstack/provision/services/BitbucketAdapter.java, src/main/java/org/opendevstack/provision/services/ConfluenceAdapter.java, src/main/java/org/opendevstack/provision/services/CrowdProjectIdentityMgmtAdapter.java, src/main/java/org/opendevstack/provision/services/JenkinsPipelineAdapter.java, src/main/java/org/opendevstack/provision/services/JiraAdapter.java, src/main/java/org/opendevstack/provision/services/StorageAdapter.java, src/test/java/org/opendevstack/provision/controller/E2EProjectAPIControllerTest.java, src/test/java/org/opendevstack/provision/controller/ProjectApiControllerTest.java, src/test/java/org/opendevstack/provision/services/AbstractBaseServiceAdapterTest.java, src/test/java/org/opendevstack/provision/services/BitbucketAdapterTest.java, src/test/java/org/opendevstack/provision/util/TestDataFileReader.java, src/test/resources/application-utest.properties, src/test/resources/e2e/bitbucket-get-admin-user-response.json, src/test/resources/e2e/bitbucket-get-group-response-template.json, src/test/resources/e2e/bitbucket-get-user-permission-project-create-response.json
=> adds pre flight checks for bitbucket

src/main/java/org/opendevstack/provision/adapter/IServiceAdapter.java, src/main/java/org/opendevstack/provision/adapter/exception/AdapterException.java, src/main/java/org/opendevstack/provision/adapter/exception/CreateProjectPreconditionException.java, src/main/java/org/opendevstack/provision/controller/ProjectApiController.java, src/main/java/org/opendevstack/provision/services/BitbucketAdapter.java, src/main/java/org/opendevstack/provision/services/ConfluenceAdapter.java, src/main/java/org/opendevstack/provision/services/CrowdProjectIdentityMgmtAdapter.java, src/main/java/org/opendevstack/provision/services/JenkinsPipelineAdapter.java, src/main/java/org/opendevstack/provision/services/JiraAdapter.java, src/main/java/org/opendevstack/provision/services/StorageAdapter.java, src/test/java/org/opendevstack/provision/controller/E2EProjectAPIControllerTest.java, src/test/java/org/opendevstack/provision/controller/ProjectApiControllerTest.java, src/test/java/org/opendevstack/provision/services/AbstractBaseServiceAdapterTest.java, src/test/java/org/opendevstack/provision/services/BitbucketAdapterTest.java, src/test/java/org/opendevstack/provision/util/TestDataFileReader.java, src/test/resources/application-utest.properties, src/test/resources/e2e/bitbucket-get-admin-user-response.json, src/test/resources/e2e/bitbucket-get-group-response-template.json, src/test/resources/e2e/bitbucket-get-user-permission-project-create-response.json
=> adds bitbucket pre flight checks backport 2.x

src/main/java/org/opendevstack/provision/adapter/exception/CreateProjectPreconditionException.java, src/main/java/org/opendevstack/provision/controller/ProjectApiController.java, src/main/java/org/opendevstack/provision/model/OpenProjectData.java, src/main/java/org/opendevstack/provision/services/BaseServiceAdapter.java, src/main/java/org/opendevstack/provision/services/BitbucketAdapter.java, src/main/java/org/opendevstack/provision/services/ConfluenceAdapter.java, src/main/java/org/opendevstack/provision/services/JenkinsPipelineAdapter.java, src/main/java/org/opendevstack/provision/services/JiraAdapter.java, src/main/java/org/opendevstack/provision/util/rest/RestClient.java, src/main/java/org/opendevstack/provision/util/rest/RestClientCall.java, src/test/java/org/opendevstack/provision/controller/E2EProjectAPIControllerTest.java, src/test/java/org/opendevstack/provision/services/BitbucketAdapterTest.java, src/test/java/org/opendevstack/provision/services/JiraAdapterTests.java, src/test/resources/e2e/bitbucket-get-user-permission-project-create-response.json, src/test/resources/e2e/jira-get-group-template.json, src/test/resources/e2e/jira-get-mypermissions-template.json, src/test/resources/e2e/jira-get-project-admin-user-response.json, src/test/resources/e2e/jira-get-user-template.json
=> adds pre flight checks for jira

src/main/java/org/opendevstack/provision/adapter/exception/CreateProjectPreconditionException.java, src/main/java/org/opendevstack/provision/controller/ProjectApiController.java, src/main/java/org/opendevstack/provision/model/OpenProjectData.java, src/main/java/org/opendevstack/provision/services/BaseServiceAdapter.java, src/main/java/org/opendevstack/provision/services/BitbucketAdapter.java, src/main/java/org/opendevstack/provision/services/ConfluenceAdapter.java, src/main/java/org/opendevstack/provision/services/JenkinsPipelineAdapter.java, src/main/java/org/opendevstack/provision/services/JiraAdapter.java, src/main/java/org/opendevstack/provision/util/rest/RestClient.java, src/main/java/org/opendevstack/provision/util/rest/RestClientCall.java, src/test/java/org/opendevstack/provision/controller/E2EProjectAPIControllerTest.java, src/test/java/org/opendevstack/provision/services/BitbucketAdapterTest.java, src/test/java/org/opendevstack/provision/services/JiraAdapterTests.java, src/test/resources/e2e/bitbucket-get-user-permission-project-create-response.json, src/test/resources/e2e/jira-get-group-template.json, src/test/resources/e2e/jira-get-mypermissions-template.json, src/test/resources/e2e/jira-get-project-admin-user-response.json, src/test/resources/e2e/jira-get-user-template.json
backport for ods 2.x 
fixes partially #330
=> adds jira pre flight checks backport 2.x

ocp-config/prov-app/cm.yml, src/main/resources/application.properties
=> enables e2e spock quickstarter backport 2.x

ocp-config/prov-app/cm.yml, src/main/resources/application.properties
=> enables e2e spock quickstarter

src/main/java/org/opendevstack/provision/controller/CheckPreconditionsResponse.java, src/main/java/org/opendevstack/provision/controller/ProjectApiController.java, src/test/java/org/opendevstack/provision/controller/CheckPreconditionsResponseTest.java, src/test/java/org/opendevstack/provision/controller/ProjectApiControllerTest.java
=> adds json response for pre condition checks

src/main/resources/logback-spring.xml
=> adds default value logback file path

ocp-config/prov-app/cm.yml, src/main/java/org/opendevstack/provision/config/Quickstarter.java, src/main/java/org/opendevstack/provision/services/BitbucketAdapter.java, src/main/resources/application.properties, src/test/java/org/opendevstack/provision/services/BitbucketAdapterTest.java, src/test/java/org/opendevstack/provision/services/JenkinsPipelineAdapterTest.java
=> add configuration for webhook creation per quickstarter

CHANGELOG.md, ocp-config/prov-app/cm.yml, src/main/java/org/opendevstack/provision/config/Quickstarter.java, src/main/java/org/opendevstack/provision/services/BitbucketAdapter.java, src/main/resources/application.properties, src/test/java/org/opendevstack/provision/services/BitbucketAdapterTest.java, src/test/java/org/opendevstack/provision/services/JenkinsPipelineAdapterTest.java
backport for 2.x for issue #392
=> add configuration for webhook creation per quickstarter 2.x backport

src/main/java/org/opendevstack/provision/authentication/oauth2/RoleAwareOAuth2UserService.java, src/test/java/org/opendevstack/provision/authentication/oauth2/RoleAwareOAuth2UserServiceTest.java
=> maps jwt roles to lowercase by default

CHANGELOG.md, src/main/java/org/opendevstack/provision/authentication/oauth2/RoleAwareOAuth2UserService.java, src/test/java/org/opendevstack/provision/authentication/oauth2/RoleAwareOAuth2UserServiceTest.java
fixes #375 
Note this change is backwards compatible
=> adds flag to opt for email claim as username

src/main/java/org/opendevstack/provision/controller/OpenProjectInfo.java, src/main/java/org/opendevstack/provision/controller/ProjectApiController.java, src/main/java/org/opendevstack/provision/services/StorageAdapter.java, src/test/java/org/opendevstack/provision/controller/ProjectApiControllerTest.java, src/test/java/org/opendevstack/provision/services/StorageAdapterTest.java
=> adds get all project summary info endpoint

src/main/java/org/opendevstack/provision/adapter/exception/CreateProjectPreconditionException.java, src/main/java/org/opendevstack/provision/controller/ProjectApiController.java, src/main/java/org/opendevstack/provision/services/BitbucketAdapter.java, src/main/java/org/opendevstack/provision/services/ConfluenceAdapter.java, src/main/java/org/opendevstack/provision/services/JiraAdapter.java, src/test/java/org/opendevstack/provision/controller/E2EProjectAPIControllerTest.java, src/test/java/org/opendevstack/provision/controller/ProjectApiControllerTest.java, src/test/java/org/opendevstack/provision/services/BitbucketAdapterTest.java, src/test/java/org/opendevstack/provision/services/ConfluenceAdapterTest.java, src/test/java/org/opendevstack/provision/services/JiraAdapterTests.java, src/test/resources/e2e/confluence-get-group-template.json, src/test/resources/e2e/confluence-get-user-template.json
=> adds confluence pre flight checks

src/main/java/org/opendevstack/provision/services/JenkinsPipelineAdapter.java, src/test/java/org/opendevstack/provision/services/JenkinsPipelineAdapterTest.java
=> includes git server url in webhook proxy build payload on create proj… -> master

ocp-config/prov-app/cm.yml
relates to and required for https://github.com/opendevstack/ods-quickstarters/pull/251
=> add be-gateway-nginx

build.gradle, docs/modules/provisioning-app/pages/configuration.adoc, src/main/java/org/opendevstack/provision/authentication/oauth2/Oauth2AuthenticationManager.java, src/main/resources/application-azure.properties, src/main/resources/application-oauth2.properties
including also
- azure properties sample
- documentation update 
- minor change that removes `keyclock` from a property
fixes #424
=> adds azure ad spring boot dependency

README.md, ocp-config/prov-app/cm.yml, src/main/java/org/opendevstack/provision/properties/ScmGlobalProperties.java, src/main/java/org/opendevstack/provision/services/BitbucketAdapter.java, src/main/resources/application.properties
That way it is easier to manage via OpenShift templates.
Closes #412.
=> Change readable repos config

Jenkinsfile, ocp-config/prov-app/bc.yml
FYI @clemensutschig @oalyman This needs more work still, but these changes allow us to finish the cd -> ods move. After this is done, we need to do one cycle with the config changes in as well to test that building the prov app actually works.
=> Align Jenkinsfile with recent changes

Jenkinsfile, src/main/resources/application.properties
Addresses https://github.com/opendevstack/ods-core/issues/523.
=> Set default branch to master instead of production

openshift/cm.yml, src/main/java/org/opendevstack/provision/services/BitbucketAdapter.java, src/main/resources/application.properties, src/test/java/org/opendevstack/provision/services/BitbucketAdapterTest.java
=> adds select pr:deleted event when creating webhooks

src/main/java/org/opendevstack/provision/services/JiraAdapter.java, src/test/java/org/opendevstack/provision/services/JiraAdapterTests.java
=> adds logic that verify if username is equals to jira emailAddress 

src/main/java/org/opendevstack/provision/controller/DefaultController.java, src/main/resources/templates/about.html
=> fixes wrong displayed username for oauth2 profile

build.gradle, sonar-project.properties
Related to https://github.com/opendevstack/ods-quickstarters/issues/213.
=> Fix SQ code coverage report

src/main/java/org/opendevstack/provision/services/JiraAdapter.java
..it points to jira but not to confluence
=> incorrect shortcut from jira to confluence

src/main/java/org/opendevstack/provision/controller/DefaultController.java, src/main/java/org/opendevstack/provision/controller/ProjectApiController.java, src/main/java/org/opendevstack/provision/services/ConfluenceAdapter.java, src/main/java/org/opendevstack/provision/services/JenkinsPipelineAdapter.java, src/test/java/org/opendevstack/provision/controller/ProjectApiControllerTest.java
=> adds option to disable confluence adapter by config

docker/Dockerfile, ocp-config/Tailorfile, ocp-config/cm.yml, ocp-config/dc.yml
=> splits qs configuration from application.configuration

src/main/java/org/opendevstack/provision/services/JenkinsPipelineAdapter.java, src/test/java/org/opendevstack/provision/services/JenkinsPipelineAdapterTest.java
Related to https://github.com/opendevstack/ods-core/pull/610.
=> Pass full URL as value of GIT_SERVER_URL

src/main/java/org/opendevstack/provision/controller/ProjectApiController.java, src/main/java/org/opendevstack/provision/controller/ProjectTemplateType.java, src/test/java/org/opendevstack/provision/controller/ProjectApiControllerTest.java
=> fixes endpoint project template key do not return json body

docs/modules/provisioning-app/pages/architecture.adoc
=> Add basic instructions how to deploy the prov app in OpenShift

ocp-config/cm.yml
recovering removed be-gateway-nginx quickstarter from cm.yml
=> get back be-gateway-nginx quickstarter

src/main/java/org/opendevstack/provision/services/BitbucketAdapter.java, src/main/java/org/opendevstack/provision/services/JiraAdapter.java, src/test/java/org/opendevstack/provision/services/BitbucketAdapterTest.java, src/test/java/org/opendevstack/provision/services/JiraAdapterTests.java, src/test/resources/e2e/bitbucket-get-admin-user-response.json
=> fixes problem with case sensitive group and username exists checks

src/main/java/org/opendevstack/provision/services/BitbucketAdapter.java, src/test/java/org/opendevstack/provision/services/BitbucketAdapterTest.java
=> Switch admin rights to write for cd user at repo level

src/main/java/org/opendevstack/provision/adapter/IServiceAdapter.java, src/main/java/org/opendevstack/provision/controller/CheckPreconditionFailure.java, src/main/java/org/opendevstack/provision/controller/CheckPreconditionsResponse.java, src/main/java/org/opendevstack/provision/controller/ProjectApiController.java, src/main/java/org/opendevstack/provision/services/BitbucketAdapter.java, src/main/java/org/opendevstack/provision/services/ConfluenceAdapter.java, src/main/java/org/opendevstack/provision/services/CrowdProjectIdentityMgmtAdapter.java, src/main/java/org/opendevstack/provision/services/JenkinsPipelineAdapter.java, src/main/java/org/opendevstack/provision/services/JiraAdapter.java, src/main/java/org/opendevstack/provision/services/StorageAdapter.java, src/test/java/org/opendevstack/provision/controller/CheckPreconditionsResponseTest.java, src/test/java/org/opendevstack/provision/controller/ProjectApiControllerTest.java, src/test/java/org/opendevstack/provision/services/BitbucketAdapterTest.java, src/test/java/org/opendevstack/provision/services/JiraAdapterTests.java
=> adds error codes to pre condition checks

ocp-config/ods-provisioning-app.env.sample
This also syncs up the env variables with ods-core.env.sample file
=> Add missing env variables

src/main/java/org/opendevstack/provision/authentication/UserRolesHolder.java, src/main/java/org/opendevstack/provision/config/AppConfig.java, src/main/java/org/opendevstack/provision/controller/API.java, src/main/java/org/opendevstack/provision/controller/ApplicationInfoAPI.java, src/main/java/org/opendevstack/provision/controller/ApplicationInfoAPIController.java, src/main/java/org/opendevstack/provision/controller/DefaultController.java, src/test/java/org/opendevstack/provision/controller/ApplicationInfoAPIControllerTest.java
=> adds application info endpoint

src/main/java/org/opendevstack/provision/model/OpenProjectDataValidator.java, src/main/resources/templates/provision.html, src/test/java/org/opendevstack/provision/model/OpenProjectDataValidatorTest.java
=> fixes invalid chars in component id: underscore, dots and numbers are not valid chars

src/main/java/org/opendevstack/provision/controller/ProjectApiController.java
=> enable preconditions checks by default, adds more logging

src/main/java/org/opendevstack/provision/config/JenkinsPipelineProperties.java, src/main/java/org/opendevstack/provision/model/OpenProjectDataValidator.java, src/main/java/org/opendevstack/provision/services/JenkinsPipelineAdapter.java, src/test/java/org/opendevstack/provision/model/OpenProjectDataValidatorTest.java, src/test/java/org/opendevstack/provision/services/JenkinsPipelineAdapterTest.java
=> fixes wrong project name validation: numbers in name are supported again

ocp-config/cm.yml
=> Remove duplicates from config maps

docs/modules/provisioning-app/pages/architecture.adoc
=> Change local java requirement in read doc

src/main/java/org/opendevstack/provision/authentication/authorization/MethodSecurityConfiguration.java, src/main/java/org/opendevstack/provision/authentication/authorization/ProvAppExpressionHandler.java, src/main/java/org/opendevstack/provision/controller/ProjectApiController.java, src/test/java/org/opendevstack/provision/authentication/TestAuthentication.java, src/test/java/org/opendevstack/provision/authentication/crowd/CrowdAuthSecurityTestConfig.java, src/test/java/org/opendevstack/provision/authentication/oauth2/MethodSecurityConfigurationTest.java, src/test/java/org/opendevstack/provision/authentication/oauth2/ProvAppExpressionHandlerTest.java, src/test/java/org/opendevstack/provision/controller/ApplicationInfoAPIControllerTest.java, src/test/java/org/opendevstack/provision/controller/ProjectApiControllerTest.java, src/test/resources/application-utestcrowd.properties
=> enables spring security authorization for crowd profile

src/main/java/org/opendevstack/provision/controller/ProjectApiController.java
=> changes default of cleanup incomplete projects config

docs/modules/provisioning-app/pages/architecture.adoc, docs/modules/provisioning-app/pages/configuration.adoc
=> adds basic auth and pre flight checks docs

docs/modules/provisioning-app/pages/architecture.adoc
=> adds provision quickstarter script to doc

src/test/java/org/opendevstack/provision/authentication/crowd/ProvAppSimpleCachingGroupMembershipManagerTest.java, src/test/java/org/opendevstack/provision/authentication/filter/SSOAuthProcessingFilterBasicAuthHandlerTest.java, src/test/java/org/opendevstack/provision/authentication/filter/SSOAuthProcessingFilterTest.java, src/test/java/org/opendevstack/provision/authentication/oauth2/MethodSecurityConfigurationTest.java, src/test/java/org/opendevstack/provision/authentication/oauth2/Oauth2AuthenticationManagerTest.java, src/test/java/org/opendevstack/provision/authentication/oauth2/ProvAppExpressionHandlerTest.java, src/test/java/org/opendevstack/provision/controller/ApplicationInfoAPIControllerTest.java, src/test/java/org/opendevstack/provision/controller/DefaultControllerTest.java, src/test/java/org/opendevstack/provision/controller/E2EProjectAPIControllerSecurityTest.java, src/test/java/org/opendevstack/provision/controller/E2EProjectAPIControllerTest.java, src/test/java/org/opendevstack/provision/controller/ProjectApiControllerTest.java, src/test/java/org/opendevstack/provision/services/BitbucketAdapterTest.java, src/test/java/org/opendevstack/provision/services/JiraAdapterTests.java, src/test/java/org/opendevstack/provision/util/rest/RestClientTest.java
Otherwise we run into ApplicationContext issues, depending on how parallel the tests are executed. E.g. tests in Jenkins failed while tests on GitHub worked.
FYI @stitakis
=> Use @DirtiesContext everywhere

client/src/app/modules/loading-indicator/components/loading-indicator.component.spec.ts
=> Unit test for loading indicator

client/README.md
=> Update client README

CODEOWNERS
=> Add client codeowner

client/src/app/modules/sidebar/components/sidebar.component.html, client/src/app/modules/sidebar/components/sidebar.component.spec.ts, client/src/app/modules/sidebar/components/sidebar.component.ts, client/src/app/modules/sidebar/sidebar.module.ts
=> Unit test for sidebar

client/src/app/modules/project-page/components/header.component.html, client/src/app/modules/project-page/components/header.component.spec.ts, client/src/app/modules/project-page/components/header.component.ts, client/src/app/modules/project-page/components/project-page.component.html, client/src/app/modules/project-page/components/quickstarter-list.component.html, client/src/app/modules/project-page/components/quickstarter-list.component.spec.ts, client/src/app/modules/project-page/components/quickstarter-list.component.ts
=> Disable new component form on non-openshift projects

client/src/app/ui/scss/components/_page.scss
=> Layoutfix Safari

client/src/app/ui/scss/theme/default/_typo.scss, client/src/index.html
incl. keep loading fonts from Google CDN for bundlesize- and perf-reasons, fixes #538
=> Font fixes

client/src/app/modules/new-project/components/new-project.component.html, client/src/app/modules/new-project/components/new-project.component.spec.ts
because all functionality should be covered by E2E tests instead, fixes #530
=> Fix basic 'new project form' test and stop adding unittests

src/main/java/org/opendevstack/provision/services/JiraAdapter.java, src/test/java/org/opendevstack/provision/services/JiraAdapterTests.java, src/test/resources/data/repositoryTestData.txt
=> fix bug on component creation

client/src/index.html
=> Acknowledge OS brightness settings

CHANGELOG.md, docs/antora.yml
required changes for release w.r.t. https://github.com/opendevstack/PMC/blob/master/releases.md#release-process-of-major-versions
=> removed prerelease from antora.yml and set date and version in changelog

CHANGELOG.md, src/main/java/org/opendevstack/provision/authentication/oauth2/RoleAwareOAuth2UserService.java
=> Fix debug level shows too much information

docs/modules/provisioning-app/pages/architecture.adoc, src/main/java/org/opendevstack/provision/util/rest/RestClient.java, src/main/resources/application-odsbox.properties, src/main/resources/application-odsbox_quickstarters.properties, src/test/java/org/opendevstack/provision/util/rest/RestClientTest.java
=> adds trust all certificates and odsbox spring profile

docs/modules/provisioning-app/pages/architecture.adoc, src/main/java/org/opendevstack/provision/util/rest/RestClient.java, src/main/resources/application-odsbox.properties, src/main/resources/application-odsbox_quickstarters.properties, src/test/java/org/opendevstack/provision/util/rest/RestClientTest.java
=> adds odsbox support and trust all certificates flag for dev envs

.github/workflows/snyk-analysis.yml
=> adds snyk scanning github actions to branch 3.x

.github/workflows/gradle.yml, .github/workflows/snyk-analysis.yml
fixes #595 
also disables snyk if secret is not available
=> fixes github build: replaces var GITHUB_REF for COMMIT_REF

src/main/java/org/opendevstack/provision/model/OpenProjectData.java, src/main/java/org/opendevstack/provision/services/BitbucketAdapter.java, src/test/java/org/opendevstack/provision/controller/E2EProjectAPIControllerTest.java, src/test/java/org/opendevstack/provision/services/BitbucketAdapterTest.java, src/test/resources/e2e/bitbucket-get-project.json
=> adds bitbucket project key precondition check

docs/modules/provisioning-app/pages/configuration.adoc, src/main/java/org/opendevstack/provision/config/JiraProjectTemplateProperties.java, src/main/java/org/opendevstack/provision/controller/CheckPreconditionFailure.java, src/main/java/org/opendevstack/provision/model/OpenProjectData.java, src/main/java/org/opendevstack/provision/model/jira/FullJiraProject.java, src/main/java/org/opendevstack/provision/model/jira/LeanJiraProject.java, src/main/java/org/opendevstack/provision/services/JiraAdapter.java, src/main/java/org/opendevstack/provision/services/RestService.java, src/main/java/org/opendevstack/provision/services/jira/ActorGroupPayload.java, src/main/java/org/opendevstack/provision/services/jira/FullJiraProjectFactory.java, src/main/java/org/opendevstack/provision/services/jira/JiraProjectPropertyUpdater.java, src/main/java/org/opendevstack/provision/services/jira/JiraProjectTemplate.java, src/main/java/org/opendevstack/provision/services/jira/JiraProjectTemplateRoleMapping.java, src/main/java/org/opendevstack/provision/services/jira/JiraProjectTypePropertyCalculator.java, src/main/java/org/opendevstack/provision/services/jira/JiraRestApi.java, src/main/java/org/opendevstack/provision/services/jira/JiraRestService.java, src/main/java/org/opendevstack/provision/services/jira/JiraSpecialPermissioner.java, src/main/java/org/opendevstack/provision/services/jira/WebhookProxyJiraPropertyUpdater.java, src/main/resources/application-odsbox.properties, src/test/java/org/opendevstack/provision/config/JiraProjectTemplatePropertiesTest.java, src/test/java/org/opendevstack/provision/controller/E2EProjectAPIControllerTest.java, src/test/java/org/opendevstack/provision/services/JiraAdapterTests.java, src/test/java/org/opendevstack/provision/services/jira/FullJiraProjectFactoryTest.java, src/test/java/org/opendevstack/provision/services/jira/JiraProjectPropertyUpdaterTest.java, src/test/java/org/opendevstack/provision/services/jira/JiraProjectTypePropertyCalculatorTest.java, src/test/java/org/opendevstack/provision/services/jira/JiraSpecialPermissionerTest.java, src/test/java/org/opendevstack/provision/services/jira/WebhookProxyJiraPropertyUpdaterTest.java, src/test/resources/application-utest.properties, src/test/resources/e2e/jira-get-permission-scheme-by-id.json, src/test/resources/e2e/jira-get-role.json
=> adds reuse jira permission scheme

CHANGELOG.md, src/main/java/org/opendevstack/provision/controller/QuickstarterApiController.java, src/test/java/org/opendevstack/provision/authentication/basic/BasicAuthSecurityTestConfig.java, src/test/java/org/opendevstack/provision/controller/ApplicationInfoAPIControllerTest.java, src/test/java/org/opendevstack/provision/controller/E2EProjectAPIControllerTest.java, src/test/java/org/opendevstack/provision/controller/QuickstarterApiControllerTest.java, src/test/resources/e2e/bitbucket-get-user-permission-project-create-response.json
completes #572 (port to master)
=> improve authorization quickstarter endpoint (port to master)

src/main/java/org/opendevstack/provision/authentication/crowd/CrowdSecurityConfiguration.java, src/main/resources/application.properties
=> increases session timeout and adds logging of session creation and expiration

src/main/java/org/opendevstack/provision/model/OpenProjectDataValidator.java, src/test/java/org/opendevstack/provision/model/OpenProjectDataValidatorTest.java
=> Updated component id reg exp to ignore tests word

CHANGELOG.md, docs/modules/provisioning-app/pages/configuration.adoc, src/main/java/org/opendevstack/provision/services/JenkinsPipelineAdapter.java, src/main/resources/application-odsbox.properties, src/test/java/org/opendevstack/provision/services/JenkinsPipelineAdapterTest.java, src/test/resources/application-utest.properties
=> Add default project groups to project groups on project creation

CHANGELOG.md, docs/modules/provisioning-app/pages/configuration.adoc, src/main/java/org/opendevstack/provision/services/JenkinsPipelineAdapter.java, src/test/java/org/opendevstack/provision/services/JenkinsPipelineAdapterTest.java, src/test/resources/application-utest.properties
=> appends default project groups to be passed on project creation

CHANGELOG.md, client/src/app/modules/app-form/config/validation.json, src/main/resources/templates/provision.html
Fixes #624 
* Updated regex and error message for the component id
* Updated error msg as per code review
* Updated regex also in the old prov-app
* Updated CHANGELOG.md
Co-authored-by: zxBCN Cruz_Martinez <felipe.cruz_martinez.ext@boehringer-ingelheim.com>
=> Updated regex and error message for the component id (#641)

CHANGELOG.md, src/main/java/org/opendevstack/provision/services/BitbucketAdapter.java, src/main/java/org/opendevstack/provision/services/ConfluenceAdapter.java
=> fixes wrong logging of exception stacktrace

.github/workflows/changelog-enforcer.yml, CHANGELOG.md
closes #657 
@stitakis you [mentioned](https://github.com/opendevstack/ods-core/issues/891#issuecomment-747949770) you would suggest to try it on ods-provisioning-app. I'd say lets try, but could you also share that info with other devs that regularly contribute to this repo?
=> added changelog enforcer action

.github/workflows/changelog-enforcer.yml
relates to https://github.com/opendevstack/ods-core/issues/891#issuecomment-747923351
=> raise version of changelog enforcer to v2 and add custom error message

CHANGELOG.md, client/src/app/modules/sidebar/components/sidebar.component.scss, client/src/app/ui/scss/_layout.scss
The searchbar input field was scrolling away with the project list
=> Fix SPA searchbar layout

CHANGELOG.md
@segator this updates the CHANGELOG with today date and version 3.0.1
To release this version, just approve the PR, merge it and then add to the branch 3.0.x a tag named "v3.0.1" -> this will trigger the build and push of the docker image to dockerhub.
=> Updates changelog with release version and date

CHANGELOG.md, src/main/java/org/opendevstack/provision/model/OpenProjectData.java, src/test/java/org/opendevstack/provision/controller/E2EProjectAPIControllerTest.java
=> API: fix bug on remove quickstarters (deleted quickstarter still returned) - master

CHANGELOG.md, src/main/java/org/opendevstack/provision/model/OpenProjectData.java, src/test/java/org/opendevstack/provision/controller/E2EProjectAPIControllerTest.java
=> Bug/remove component - for 4x

CHANGELOG.md, src/main/java/org/opendevstack/provision/controller/ProjectApiController.java, src/main/java/org/opendevstack/provision/services/JenkinsPipelineAdapter.java, src/test/java/org/opendevstack/provision/controller/E2EProjectAPIControllerTest.java, src/test/java/org/opendevstack/provision/model/OpenProjectDataTest.java
closes jenkins shared lib #790 (https://github.com/opendevstack/ods-jenkins-shared-library/issues/790) for master
=> fix wrong execution job on DELETE API - for master

docs/modules/provisioning-app/pages/architecture.adoc, docs/modules/provisioning-app/pages/configuration.adoc, docs/modules/provisioning-app/pages/index.adoc
Fix antora3 errors and warnings.
Fixes: https://github.com/opendevstack/ods-provisioning-app/issues/719
https://github.com/opendevstack/ods-documentation/issues/66
=> [ci skip] fix xref and properly escape special character for asciidoc

CHANGELOG.md, docs/modules/provisioning-app/pages/configuration.adoc, src/main/java/org/opendevstack/provision/config/OpenshiftServiceConfig.java, src/test/java/org/opendevstack/provision/config/OpenshiftServiceConfigTest.java
=> disables by default the openshift client service

CHANGELOG.md, docs/modules/provisioning-app/pages/configuration.adoc, src/main/java/org/opendevstack/provision/config/OpenshiftServiceConfig.java, src/test/java/org/opendevstack/provision/config/OpenshiftServiceConfigTest.java
=> reverts enable openshift service by default

CHANGELOG.md, build.gradle
=> ODS AMI Build quickstarter prov app fails due to no nexus equal false

CHANGELOG.md, Jenkinsfile, build.gradle
=> Fixes deprecated libraries problem
